# -*- coding: utf-8 -*-
"""ΑΣΚΗΣΗ_ΚΩΔΙΚΑ_ΕΝΟΤΗΤΑ_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V00iL2_3tEev6rnjHrIx-ms-ktF6jeTr
"""

#CODE ENOTITAS_3
s = input("enter a string choice: ")
print()


if len(s)==1:
  print("the length is only one character from string to put from user ---ΜΗΚΟΣ=1---")
else:
  if(s==s[::-1]):
      #create a dict
      adict= {s:len(s)}
      print(adict)
      print()

      #create a list
      alist=list(s)
      print(alist)
      print()
      #output a message
      print("The string is a palindrome")
  else:
      print("Not a palindrome")