# -*- coding: utf-8 -*-
"""ΑΣΚΗΣΗ_ΚΩΔΙΚΑ_ΕΝΟΤΗΤΑΣ_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_AR9l8pdXrk-mIS40GEIWwIIFMxg7kfs
"""

# Python Program to Check Leap Year using If Statement

year = int(input("Please Enter the Year Number you wish (with four digits): "))

print()

#check value with simple if for leap or not year
if (( year%400 == 0)or (( year%4 == 0 ) and ( year%100 != 0))):
    disekto = True
    print(disekto)
    print("%d is a Leap Year" %year)
else:
    disekto = False
    print(disekto)
    print("%d is Not the Leap Year" %year)