# -*- coding: utf-8 -*-
"""enotita5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pMA5-8HWyGSNiYDdDIu0-cn8BhbdzHFt
"""

import statistics as stats

# Read csv file
input_data = []
with open("inputdata.txt", "r") as f:
  for line in f.readlines():
    # Making sure that lines are floats
    input_data.append(float(line))
  # Print list of floats
  print (input_data)
# Close file
f.close()

# Calculating mean and std values
mean_value = stats.mean(input_data)
std_value = stats.stdev(input_data)

# Printing results with no specific decimal such as outputdata file
print ('Mean value = {}'.format(mean_value))
print ('Std value = {}'.format(std_value))

# Write results to outputdata.txt
with open("outputdata.txt", 'w') as f:
  f.write('Mean value = {0:.3f}\n'.format(mean_value))
  f.write('Std value = {0:.3f}'.format(std_value))
# Close file
f.close()