# -*- coding: utf-8 -*-
"""enotita_coding4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-aZ3WwI_4kuuqSBvL2ohqA1VTi1ZJr1g
"""

from statistics import mean

def squares(*args):
    """
    A function that calculates the square of the difference with the mean value of args.
    
    Yields:
        [float] -- squares of the difference with the mean value of args.
    """
    try:
        # Calculate mean value
        mean_value = mean(args)
        # Loop once to args and calculate the values    
        for a in args:
            yield (a-mean_value) ** 2
    # In case of 0 args
    except:
        return

# Call function
res = squares(1, 2, 3)
res_next = squares(2,7,3,12)

# Print results
for i in res:
    print (i)

print()

for i in res_next:
  print(i)